import "./globals.css";
import NavBar from "@/Components/NavBar";
import Footer from "@/Components/Footer";
import { UseStoreContextProvider } from "@/Context/UseStoreContext";
import { UserAuthContexProvider } from "@/Context/UserAuthContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"
        />
      </head>
      <body>
        <UseStoreContextProvider>
          <UserAuthContexProvider>
            <Toaster />
            <NavBar />
            <main className=" px-5 md:px-0 container  pb-5 pt-36  md:pt-24  m-auto  text-xs md:text-sm  ">
              {children}
            </main>
            <Footer />
          </UserAuthContexProvider>
        </UseStoreContextProvider>
      </body>
    </html>
  );
}
